In [2]:
print("test")

test

In [1]:
%pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp313-cp313-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 55.2 MB/s  0:00:00m0:00:0100:01
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             46 bits physical, 57 bits virtual
  Byte Order:                Little Endian
CPU(s):                      16
  On-line CPU(s) list:       0-15
Vendor ID:                   GenuineIntel
  Model name:                Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    CPU family:              6
    Model:                   106
    Thread(s) per core:      2
    Core(s) per socket:      8
    Socket(s):               1
    Stepping:                6
    CPU(s) scaling MHz:      99%
    CPU max MHz:             2800.0000
    CPU min MHz:             800.0000
    BogoMIPS:                5586.87
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush mmx fxsr sse sse2 ss h
                             t syscall nx pdpe1gb rdtscp lm constant_tsc rep_goo
                             d nopl xtopology tsc_reliable nonstop_tsc cpuid ape
                             rfmperf tsc_known_freq pni pclmulqdq vmx ssse3 fma
                             cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_dea
                             dline_timer aes xsave avx f16c rdrand hypervisor la
                             hf_lm abm 3dnowprefetch invpcid_single tpr_shadow v
                             nmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle av
                             x2 smep bmi2 erms invpcid rtm avx512f avx512dq rdse
                             ed adx smap avx512ifma clflushopt clwb avx512cd sha
                             _ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsave
                             s avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq
                              avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rd
                             pid fsrm arch_capabilities
Virtualization features:
  Virtualization:            VT-x
  Hypervisor vendor:         Microsoft
  Virtualization type:       full
Caches (sum of all):
  L1d:                       384 KiB (8 instances)
  L1i:                       256 KiB (8 instances)
  L2:                        10 MiB (8 instances)
  L3:                        48 MiB (1 instance)
NUMA:
  NUMA node(s):              1
  NUMA node0 CPU(s):         0-15
Vulnerabilities:
  Gather data sampling:      Not affected
  Indirect target selection: Mitigation; Aligned branch/return thunks
  Itlb multihit:             Not affected
  L1tf:                      Not affected
  Mds:                       Not affected
  Meltdown:                  Not affected
  Mmio stale data:           Vulnerable: Clear CPU buffers attempted, no microco
                             de; SMT Host state unknown
  Reg file data sampling:    Not affected
  Retbleed:                  Vulnerable
  Spec rstack overflow:      Not affected
  Spec store bypass:         Vulnerable
  Spectre v1:                Mitigation; usercopy/swapgs barriers and __user poi
                             nter sanitization
  Spectre v2:                Mitigation; Retpolines; STIBP disabled; RSB filling
                             ; PBRSB-eIBRS Not affected; BHI Retpoline
  Srbds:                     Not affected
  Tsa:                       Not affected
  Tsx async abort:           Not affected
  Vmscape:                   Not affected

In [3]:
%pip install pandas

Requirement already satisfied: pandas in /layers/paketo-buildpacks_poetry-install/poetry-venv/datascience-python-renku-dependencies-xS3fZVNL-py3.13/lib/python3.13/site-packages (3.0.4)
Requirement already satisfied: numpy>=1.26.0 in /layers/paketo-buildpacks_poetry-install/poetry-venv/datascience-python-renku-dependencies-xS3fZVNL-py3.13/lib/python3.13/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /layers/paketo-buildpacks_poetry-install/poetry-venv/datascience-python-renku-dependencies-xS3fZVNL-py3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /layers/paketo-buildpacks_poetry-install/poetry-venv/datascience-python-renku-dependencies-xS3fZVNL-py3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [14]:
import pandas as pd

df = pd.read_csv("../../aew-data/test-blob/input_data/HackDays2026 - GIGI.csv", sep=";")

df.head()

,GP-Nr,PLZ,Ort,Kanton,WärmePumpe,PV,PV-Leistung in kWp,Batterie/Speicher,Ladestation für Elektrofahrzeuge,Wärmepumpenboiler,Datum Unterschrift,geplanter Baustart,Übergabe,InBetrieb-Datum
0,698970,5452.0,Oberrohrdorf,AG,-,x,NaN,-,-,-,18.04.2008,NaN,NaN,NaN
1,NaN,5024.0,Küttigen,AG,-,-,NaN,-,-,-,01.01.2017,NaN,NaN,NaN
2,196344,5732.0,Zetzwil,AG,-,-,NaN,-,-,-,01.01.2017,NaN,NaN,21.06.2017
3,570021,5023.0,Biberstein,AG,x,-,NaN,-,-,-,01.07.2017,NaN,NaN,24.11.2017
4,716671,8962.0,Bergdietikon,AG,x,x,NaN,x,-,-,24.08.2017,NaN,23.11.2017,04.12.2017

/home/renku/work/OSNOVA/dataanalysis

In [ ]:
from pathlib import Path
import pandas as pd

source = Path("../../aew-data/test-blob/input_data")
target = Path("../../store/parquet_data")

for csv_file in source.rglob("*.csv"):
    relative = csv_file.relative_to(source)
    parquet_file = target / relative.with_suffix(".parquet")

    parquet_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        # Your GIGI file uses ;
        df = pd.read_csv(csv_file, sep=";")

        # Clean column names
        df.columns = df.columns.str.strip()

        df.to_parquet(
            parquet_file,
            engine="pyarrow",
            compression="snappy",
            index=False
        )

        print(f"Converted: {csv_file} -> {parquet_file}")

    except Exception as e:
        print(f"FAILED: {csv_file}")
        print(e)

Converted: ../../aew-data/test-blob/input_data/HackDays2026 - GIGI.csv -> ../../store/parquet_data/HackDays2026 - GIGI.parquet
Converted: ../../aew-data/test-blob/input_data/Zähler-GP.csv -> ../../store/parquet_data/Zähler-GP.parquet
Converted: ../../aew-data/test-blob/input_data/mpid_zähler_mapping.csv -> ../../store/parquet_data/mpid_zähler_mapping.parquet
Converted: ../../aew-data/test-blob/input_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.csv -> ../../store/parquet_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.csv -> ../../store/parquet_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.csv -> ../../store/parquet_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.csv -> ../../store/parquet_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.csv -> ../../store/parquet_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.csv -> ../../store/parquet_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.parquet
Converted: ../../aew-data/test-blob/input_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.csv -> ../../store/parquet_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.parquet
Converted: ../../aew-data/test-blob/input_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.csv -> ../../store/parquet_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.parquet
Converted: ../../aew-data/test-blob/input_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.csv -> ../../store/parquet_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.csv -> ../../store/parquet_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.csv -> ../../store/parquet_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.csv -> ../../store/parquet_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.csv -> ../../store/parquet_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.csv -> ../../store/parquet_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.csv -> ../../store/parquet_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.parquet
Converted: ../../aew-data/test-blob/input_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.csv -> ../../store/parquet_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.parquet
Converted: ../../aew-data/test-blob/input_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.csv -> ../../store/parquet_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.csv -> ../../store/parquet_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.parquet
Converted: ../../aew-data/test-blob/input_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.csv -> ../../store/parquet_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.parquet
Converted: ../../aew-data/test-blob/input_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.csv -> ../../store/parquet_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.parquet
Converted: ../../aew-data/test-blob/input_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.csv -> ../../store/parquet_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.parquet

In [ ]:
from pathlib import Path
import pandas as pd

source = Path("../../aew-data/test-blob/input_data")
target = Path("../../store/parquet_data")

skip_years = {}

for csv_file in source.rglob("*.csv"):
    relative = csv_file.relative_to(source)

    # Skip anything inside 2025 or 2026 folders
    if any(part in skip_years for part in relative.parts):
        print(f"SKIPPED YEAR: {csv_file}")
        continue

    parquet_file = target / relative.with_suffix(".parquet")
    parquet_file.parent.mkdir(parents=True, exist_ok=True)

    # Skip files that were already converted
    if parquet_file.exists():
        print(f"ALREADY EXISTS: {parquet_file}")
        continue

    try:
        df = pd.read_csv(csv_file, sep=";")
        df.columns = df.columns.str.strip()

        df.to_parquet(
            parquet_file,
            engine="pyarrow",
            compression="snappy",
            index=False
        )

        print(f"Converted: {csv_file} -> {parquet_file}")

    except Exception as e:
        print(f"FAILED: {csv_file}")
        print(e)

print("done")

ALREADY EXISTS: ../../store/parquet_data/HackDays2026 - GIGI.parquet
ALREADY EXISTS: ../../store/parquet_data/Zähler-GP.parquet
ALREADY EXISTS: ../../store/parquet_data/mpid_zähler_mapping.parquet
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.csv
SKIPPED YEAR: ../../aew-data/test-blob/input_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.csv
ALREADY EXISTS: ../../store/parquet_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Dezember 2024/LG_AIM2Hackerdays_kWh_20260822_063349.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Februar 2024/LG_AIM2Hackerdays_kWh_20260811_062000.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.csv -> ../../store/parquet_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.csv -> ../../store/parquet_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.csv -> ../../store/parquet_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.csv -> ../../store/parquet_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.parquet
Converted: ../../aew-data/test-blob/input_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.csv -> ../../store/parquet_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.parquet
Converted: ../../aew-data/test-blob/input_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.csv -> ../../store/parquet_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.csv -> ../../store/parquet_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.parquet
Converted: ../../aew-data/test-blob/input_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.csv -> ../../store/parquet_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.csv -> ../../store/parquet_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.csv -> ../../store/parquet_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.csv -> ../../store/parquet_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.csv -> ../../store/parquet_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.csv -> ../../store/parquet_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.csv -> ../../store/parquet_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.csv -> ../../store/parquet_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.csv -> ../../store/parquet_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.csv -> ../../store/parquet_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.csv -> ../../store/parquet_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.csv -> ../../store/parquet_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.parquet
Converted: ../../aew-data/test-blob/input_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.csv -> ../../store/parquet_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.parquet
done

In [4]:
from pathlib import Path
import pandas as pd
import csv

source = Path("../../aew-data/test-blob/input_data")
target = Path("../../store/parquet_data")

wanted_years = {"2023", "2024"}

for csv_file in source.rglob("*.csv"):
    relative = csv_file.relative_to(source)

    # Only process 2023 and 2024
    year = next(
        (part for part in relative.parts if part in wanted_years),
        None
    )

    if year is None:
        print(f"SKIPPED: {csv_file}")
        continue

    parquet_file = target / relative.with_suffix(".parquet")
    parquet_file.parent.mkdir(parents=True, exist_ok=True)

    # 2024 files can be skipped if already converted.
    # 2023 files are intentionally overwritten because we need to fix them.
    if year == "2024" and parquet_file.exists():
        print(f"ALREADY EXISTS: {parquet_file}")
        continue

    try:
        if year == "2023":
            # Read header ourselves
            with open(csv_file, "r", encoding="utf-8-sig") as f:
                reader = csv.reader(f, delimiter=";")
                header = next(reader)

            # Remove trailing empty header caused by final ;
            if header and header[-1] == "":
                header = header[:-1]

            # Read data without trusting the malformed header
            df = pd.read_csv(
                csv_file,
                sep=";",
                header=None,
                skiprows=1
            )

            # Remove trailing empty column caused by final ;
            if df.iloc[:, -1].isna().all():
                df = df.iloc[:, :-1]

            # 2023 has an extra second column.
            # Remove it.
            df = df.drop(columns=df.columns[1])

            # Verify that everything now lines up
            if len(df.columns) != len(header):
                raise ValueError(
                    f"Column mismatch after 2023 fix: "
                    f"{len(df.columns)} data columns vs "
                    f"{len(header)} header columns"
                )

            df.columns = header

            print(
                f"2023 FIX: removed extra identifier column "
                f"from {csv_file.name}"
            )

        else:
            # Normal 2024 structure
            df = pd.read_csv(csv_file, sep=";")

            # Remove completely empty trailing column, if present
            unnamed = [
                col for col in df.columns
                if str(col).startswith("Unnamed:")
            ]

            if unnamed:
                df = df.drop(columns=unnamed)

        # Clean whitespace from column names
        df.columns = df.columns.str.strip()

        df.to_parquet(
            parquet_file,
            engine="pyarrow",
            compression="snappy",
            index=False
        )

        print(f"Converted: {csv_file} -> {parquet_file}")

    except Exception as e:
        print(f"FAILED: {csv_file}")
        print(e)

SKIPPED: ../../aew-data/test-blob/input_data/HackDays2026 - GIGI.csv
SKIPPED: ../../aew-data/test-blob/input_data/Zähler-GP.csv
SKIPPED: ../../aew-data/test-blob/input_data/mpid_zähler_mapping.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.csv
SKIPPED: ../../aew-data/test-blob/input_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.csv
SKIPPED: ../../aew-data/test-blob/input_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.csv
ALREADY EXISTS: ../../store/parquet_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Dezember 2024/LG_AIM2Hackerdays_kWh_20260822_063349.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Februar 2024/LG_AIM2Hackerdays_kWh_20260811_062000.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.parquet
ALREADY EXISTS: ../../store/parquet_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260826_201441.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.csv -> ../../store/parquet_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260828_151916.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.csv -> ../../store/parquet_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260830_205227.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.csv -> ../../store/parquet_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260825_152222.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.csv -> ../../store/parquet_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260825_131305.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.csv -> ../../store/parquet_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260828_124337.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.csv -> ../../store/parquet_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260827_211912.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.csv -> ../../store/parquet_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260827_144609.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.csv -> ../../store/parquet_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260827_084034.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.csv -> ../../store/parquet_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260830_162012.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.csv -> ../../store/parquet_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260830_112533.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.csv -> ../../store/parquet_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.parquet
2023 FIX: removed extra identifier column from LG_AIM2Hackerdays_kWh_20260829_055849.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.csv -> ../../store/parquet_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.parquet

In [2]:
from pathlib import Path
import pandas as pd
import re

root = Path("../../store/parquet_data")

negative_rows = []
file_summary = []

# Matches columns such as 00:15, 13:30, 23:45, 00:00
time_pattern = re.compile(r"^\d{2}:\d{2}$")

for parquet_file in root.rglob("*.parquet"):
    try:
        df = pd.read_parquet(parquet_file)

        # Find only quarter-hour measurement columns
        time_cols = [
            col for col in df.columns
            if time_pattern.match(str(col))
        ]

        if not time_cols:
            print(f"SKIPPED (no time columns): {parquet_file}")
            continue

        # Ensure values are numeric
        values = df[time_cols].apply(pd.to_numeric, errors="coerce")

        # Boolean matrix: True wherever value < 0
        negative_mask = values < 0
        negative_count = int(negative_mask.sum().sum())

        file_summary.append({
            "file": str(parquet_file),
            "rows": len(df),
            "negative_values": negative_count
        })

        if negative_count > 0:
            print(f"NEGATIVE: {negative_count:>6} values in {parquet_file}")

            # Get positions of every negative value
            row_indices, col_indices = negative_mask.to_numpy().nonzero()

            for row_idx, col_idx in zip(row_indices, col_indices):
                time_col = time_cols[col_idx]

                negative_rows.append({
                    "file": str(parquet_file),
                    "MP ID": df.iloc[row_idx].get("MP ID"),
                    "OBIS-Code": df.iloc[row_idx].get("OBIS-Code"),
                    "Datum": df.iloc[row_idx].get("Datum"),
                    "PLZ": df.iloc[row_idx].get("PLZ"),
                    "time": time_col,
                    "value_kWh": values.iloc[row_idx, col_idx]
                })

        else:
            print(f"OK: {parquet_file}")

    except Exception as e:
        print(f"FAILED: {parquet_file}")
        print(e)

# Results
summary = pd.DataFrame(file_summary)
negatives = pd.DataFrame(negative_rows)

print("\n=============================")
print("TOTAL NEGATIVE VALUES:", len(negatives))
print("=============================")

negatives

SKIPPED (no time columns): ../../store/parquet_data/HackDays2026 - GIGI.parquet
SKIPPED (no time columns): ../../store/parquet_data/mpid_zähler_mapping.parquet
SKIPPED (no time columns): ../../store/parquet_data/Zähler-GP.parquet
NEGATIVE:      4 values in ../../store/parquet_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.parquet
NEGATIVE:      1 values in ../../store/parquet_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.parquet
NEGATIVE:      2 values in ../../store/parquet_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.parquet
NEGATIVE:      3 values in ../../store/parquet_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.parquet
NEGATIVE:      1 values in ../../store/parquet_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.parquet
NEGATIVE:     13 values in ../../store/parquet_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.parquet
NEGATIVE:      2 values in ../../store/parquet_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.parquet
NEGATIVE:    110 values in ../../store/parquet_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.parquet
NEGATIVE:    107 values in ../../store/parquet_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.parquet
NEGATIVE:      1 values in ../../store/parquet_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.parquet
NEGATIVE:     62 values in ../../store/parquet_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.parquet
NEGATIVE:     72 values in ../../store/parquet_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.parquet
NEGATIVE:     95 values in ../../store/parquet_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.parquet
NEGATIVE:    113 values in ../../store/parquet_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.parquet
NEGATIVE:    114 values in ../../store/parquet_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.parquet
NEGATIVE:     90 values in ../../store/parquet_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.parquet
NEGATIVE:      1 values in ../../store/parquet_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.parquet
NEGATIVE:      8 values in ../../store/parquet_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.parquet
NEGATIVE:     13 values in ../../store/parquet_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.parquet
NEGATIVE:     99 values in ../../store/parquet_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.parquet
NEGATIVE:     58 values in ../../store/parquet_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.parquet
NEGATIVE:     63 values in ../../store/parquet_data/2024/Dezember 2024/LG_AIM2Hackerdays_kWh_20260822_063349.parquet
NEGATIVE:    111 values in ../../store/parquet_data/2024/Februar 2024/LG_AIM2Hackerdays_kWh_20260811_062000.parquet
NEGATIVE:    101 values in ../../store/parquet_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.parquet
NEGATIVE:     51 values in ../../store/parquet_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.parquet
NEGATIVE:     64 values in ../../store/parquet_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.parquet
NEGATIVE:     79 values in ../../store/parquet_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.parquet
NEGATIVE:    104 values in ../../store/parquet_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.parquet
NEGATIVE:     65 values in ../../store/parquet_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.parquet
NEGATIVE:     56 values in ../../store/parquet_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.parquet
NEGATIVE:     86 values in ../../store/parquet_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.parquet
NEGATIVE:      3 values in ../../store/parquet_data/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.parquet
NEGATIVE:     10 values in ../../store/parquet_data/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.parquet
NEGATIVE:    111 values in ../../store/parquet_data/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.parquet
NEGATIVE:      4 values in ../../store/parquet_data/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.parquet
NEGATIVE:      6 values in ../../store/parquet_data/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.parquet
NEGATIVE:     17 values in ../../store/parquet_data/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.parquet
OK: ../../store/parquet_data/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.parquet
NEGATIVE:      5 values in ../../store/parquet_data/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.parquet
NEGATIVE:     11 values in ../../store/parquet_data/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.parquet
NEGATIVE:      3 values in ../../store/parquet_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.parquet
NEGATIVE:     10 values in ../../store/parquet_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.parquet
NEGATIVE:    111 values in ../../store/parquet_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.parquet
NEGATIVE:      4 values in ../../store/parquet_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.parquet
NEGATIVE:      6 values in ../../store/parquet_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.parquet
NEGATIVE:     17 values in ../../store/parquet_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.parquet
NEGATIVE:      9 values in ../../store/parquet_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.parquet
OK: ../../store/parquet_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.parquet
NEGATIVE:      5 values in ../../store/parquet_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.parquet
NEGATIVE:     11 values in ../../store/parquet_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.parquet

=============================
TOTAL NEGATIVE VALUES: 2137
=============================

,file,MP ID,OBIS-Code,Datum,PLZ,time,value_kWh
0,../../store/parquet_data/2026/April 2026/LG_AI...,95183,1-1:1.29.0*255,23.04.2026,5304.0,04:15,-0.017
1,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:1.29.0*255,28.04.2026,5236.0,01:15,-16777.216
2,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:2.29.0*255,29.04.2026,5236.0,20:15,-0.256
3,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:2.29.0*255,29.04.2026,5236.0,20:45,-16777.216
4,../../store/parquet_data/2026/Februar 2026/LG_...,105491,1-1:1.29.0*255,28.02.2026,5504.0,04:15,-2.615
...,...,...,...,...,...,...,...
2132,../../store/parquet_data/2023/2023/September 2...,61016,1-1:1.29.0*255,04.09.2023,4310.0,05:00,-0.314
2133,../../store/parquet_data/2023/2023/September 2...,31024,1-1:1.29.0*255,30.09.2023,5726.0,23:45,-6.670
2134,../../store/parquet_data/2023/2023/September 2...,40887,1-1:1.29.0*255,02.09.2023,4310.0,10:30,-1.555
2135,../../store/parquet_data/2023/2023/September 2...,40887,1-1:1.29.0*255,12.09.2023,4310.0,11:00,-0.426
2136,../../store/parquet_data/2023/2023/September 2...,26103,1-1:1.29.0*255,15.09.2023,5313.0,13:15,-0.321

In [13]:
from pathlib import Path
import pandas as pd
import csv

source = Path("../../aew-data/test-blob/input_data")
target = Path("../../store/parquet_data")

for csv_file in source.rglob("*.csv"):
    relative = csv_file.relative_to(source)

    # Detect whether this file belongs to 2023
    year = next(
        (part for part in relative.parts if part.isdigit() and len(part) == 4),
        None
    )

    parquet_file = target / relative.with_suffix(".parquet")
    parquet_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        if year == "2023":
            # Read header ourselves because the 2023 CSV structure is malformed
            with open(csv_file, "r", encoding="utf-8-sig") as f:
                reader = csv.reader(f, delimiter=";")
                header = next(reader)

            # Remove trailing empty header caused by a final ;
            if header and header[-1] == "":
                header = header[:-1]

            # Read the data without trusting the malformed header
            df = pd.read_csv(
                csv_file,
                sep=";",
                header=None,
                skiprows=1
            )

            # Remove trailing completely empty column caused by a final ;
            if len(df.columns) > 0 and df.iloc[:, -1].isna().all():
                df = df.iloc[:, :-1]

            # 2023 has an extra second column.
            # Remove it.
            if len(df.columns) < 2:
                raise ValueError(
                    f"2023 file has fewer than 2 columns: {csv_file}"
                )

            df = df.drop(columns=df.columns[1])

            # Verify that the corrected data matches the header
            if len(df.columns) != len(header):
                raise ValueError(
                    f"Column mismatch after 2023 fix: "
                    f"{len(df.columns)} data columns vs "
                    f"{len(header)} header columns "
                    f"in {csv_file}"
                )

            df.columns = header

            print(
                f"2023 FIX: removed extra second column "
                f"from {csv_file.name}"
            )

        else:
            # Normal structure for all other years
            df = pd.read_csv(
                csv_file,
                sep=";"
            )

            # Remove completely empty trailing columns created by a final ;
            unnamed = [
                col for col in df.columns
                if str(col).startswith("Unnamed:")
                and df[col].isna().all()
            ]

            if unnamed:
                df = df.drop(columns=unnamed)

        # Clean whitespace from column names
        df.columns = df.columns.astype(str).str.strip()

        # Always overwrite/reconvert the parquet file
        df.to_parquet(
            parquet_file,
            engine="pyarrow",
            compression="snappy",
            index=False
        )

        print(f"Converted: {csv_file} -> {parquet_file}")

    except Exception as e:
        print(f"FAILED: {csv_file}")
        print(f"{type(e).__name__}: {e}")

print("done")

Converted: ../../aew-data/test-blob/input_data/HackDays2026 - GIGI.csv -> ../../store/parquet_data/HackDays2026 - GIGI.parquet
Converted: ../../aew-data/test-blob/input_data/Zähler-GP.csv -> ../../store/parquet_data/Zähler-GP.parquet
Converted: ../../aew-data/test-blob/input_data/mpid_zähler_mapping.csv -> ../../store/parquet_data/mpid_zähler_mapping.parquet
Converted: ../../aew-data/test-blob/input_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.csv -> ../../store/parquet_data/2026/April 2026/LG_AIM2Hackerdays_kWh_20260728_140238.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.csv -> ../../store/parquet_data/2026/Februar 2026/LG_AIM2Hackerdays_kWh_20260727_130937.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.csv -> ../../store/parquet_data/2026/Januar 2026/LG_AIM2Hackerdays_kWh_20260727_065429.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.csv -> ../../store/parquet_data/2026/Juli 2026/LG_AIM2Hackerdays_kWh_20260824_102023.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.csv -> ../../store/parquet_data/2026/Juni 2026/LG_AIM2Hackerdays_kWh_20260729_062053.parquet
Converted: ../../aew-data/test-blob/input_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.csv -> ../../store/parquet_data/2026/Mai 2026/LG_AIM2Hackerdays_kWh_20260728_195653.parquet
Converted: ../../aew-data/test-blob/input_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.csv -> ../../store/parquet_data/2026/März 2026/LG_AIM2Hackerdays_kWh_20260728_063802.parquet
Converted: ../../aew-data/test-blob/input_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.csv -> ../../store/parquet_data/2025/April 2025/LG_AIM2Hackerdays_kWh_20260730_181422.parquet
Converted: ../../aew-data/test-blob/input_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.csv -> ../../store/parquet_data/2025/August 2025/LG_AIM2Hackerdays_kWh_20260801_174011.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.csv -> ../../store/parquet_data/2025/Dezember 2025/LG_AIM2Hackerdays_kWh_20260805_065742.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.csv -> ../../store/parquet_data/2025/Februar 2025/LG_AIM2Hackerdays_kWh_20260730_061341.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.csv -> ../../store/parquet_data/2025/Januar 2025/LG_AIM2Hackerdays_kWh_20260729_151030.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.csv -> ../../store/parquet_data/2025/Juli 2025/LG_AIM2Hackerdays_kWh_20260801_063453.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.csv -> ../../store/parquet_data/2025/Juni 2025/LG_AIM2Hackerdays_kWh_20260731_133938.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.csv -> ../../store/parquet_data/2025/Mai 2025/LG_AIM2Hackerdays_kWh_20260731_065533.parquet
Converted: ../../aew-data/test-blob/input_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.csv -> ../../store/parquet_data/2025/März 2025/LG_AIM2Hackerdays_kWh_20260730_141924.parquet
Converted: ../../aew-data/test-blob/input_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.csv -> ../../store/parquet_data/2025/November 2025/LG_AIM2Hackerdays_kWh_20260804_115542.parquet
Converted: ../../aew-data/test-blob/input_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.csv -> ../../store/parquet_data/2025/Oktober 2025/LG_AIM2Hackerdays_kWh_20260802_162640.parquet
Converted: ../../aew-data/test-blob/input_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.csv -> ../../store/parquet_data/2025/September 2025/LG_AIM2Hackerdays_kWh_20260802_085319.parquet
Converted: ../../aew-data/test-blob/input_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.csv -> ../../store/parquet_data/2024/April 2024/LG_AIM2Hackerdays_kWh_20260812_070837.parquet
Converted: ../../aew-data/test-blob/input_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.csv -> ../../store/parquet_data/2024/August 2024/LG_AIM2Hackerdays_kWh_20260814_133937.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Dezember 2024/LG_AIM2Hackerdays_kWh_20260822_063349.csv -> ../../store/parquet_data/2024/Dezember 2024/LG_AIM2Hackerdays_kWh_20260822_063349.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Februar 2024/LG_AIM2Hackerdays_kWh_20260811_062000.csv -> ../../store/parquet_data/2024/Februar 2024/LG_AIM2Hackerdays_kWh_20260811_062000.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.csv -> ../../store/parquet_data/2024/Januar 2024/LG_AIM2Hackerdays_kWh_20260807_062250.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.csv -> ../../store/parquet_data/2024/Juli 2024/LG_AIM2Hackerdays_kWh_20260814_064940.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.csv -> ../../store/parquet_data/2024/Juni 2024/LG_AIM2Hackerdays_kWh_20260813_095327.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.csv -> ../../store/parquet_data/2024/Mai 2024/LG_AIM2Hackerdays_kWh_20260812_124247.parquet
Converted: ../../aew-data/test-blob/input_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.csv -> ../../store/parquet_data/2024/März 2024/LG_AIM2Hackerdays_kWh_20260811_114208.parquet
Converted: ../../aew-data/test-blob/input_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.csv -> ../../store/parquet_data/2024/November 2024/LG_AIM2Hackerdays_kWh_20260821_060854.parquet
Converted: ../../aew-data/test-blob/input_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.csv -> ../../store/parquet_data/2024/Oktober 2024/LG_AIM2Hackerdays_kWh_20260820_084220.parquet
Converted: ../../aew-data/test-blob/input_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.csv -> ../../store/parquet_data/2024/September 2024/LG_AIM2Hackerdays_kWh_20260819_124455.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260826_201441.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.csv -> ../../store/parquet_data/2023/2023/April 2023/LG_AIM2Hackerdays_kWh_20260826_201441.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260828_151916.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.csv -> ../../store/parquet_data/2023/2023/August 2023/LG_AIM2Hackerdays_kWh_20260828_151916.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260830_205227.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.csv -> ../../store/parquet_data/2023/2023/Dezember 2023/LG_AIM2Hackerdays_kWh_20260830_205227.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260825_152222.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.csv -> ../../store/parquet_data/2023/2023/Februar 2023/LG_AIM2Hackerdays_kWh_20260825_152222.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260825_131305.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.csv -> ../../store/parquet_data/2023/2023/Januar 2023/LG_AIM2Hackerdays_kWh_20260825_131305.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260828_124337.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.csv -> ../../store/parquet_data/2023/2023/Juli 2023/LG_AIM2Hackerdays_kWh_20260828_124337.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260827_211912.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.csv -> ../../store/parquet_data/2023/2023/Juni 2023/LG_AIM2Hackerdays_kWh_20260827_211912.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260827_144609.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.csv -> ../../store/parquet_data/2023/2023/Mai 2023/LG_AIM2Hackerdays_kWh_20260827_144609.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260827_084034.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.csv -> ../../store/parquet_data/2023/2023/März 2023/LG_AIM2Hackerdays_kWh_20260827_084034.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260830_162012.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.csv -> ../../store/parquet_data/2023/2023/November 2023/LG_AIM2Hackerdays_kWh_20260830_162012.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260830_112533.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.csv -> ../../store/parquet_data/2023/2023/Oktober 2023/LG_AIM2Hackerdays_kWh_20260830_112533.parquet
2023 FIX: removed extra second column from LG_AIM2Hackerdays_kWh_20260829_055849.csv
Converted: ../../aew-data/test-blob/input_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.csv -> ../../store/parquet_data/2023/2023/September 2023/LG_AIM2Hackerdays_kWh_20260829_055849.parquet
done

In [ ]:
negatives[]

,file,MP ID,OBIS-Code,Datum,PLZ,time,value_kWh
0,../../store/parquet_data/2026/April 2026/LG_AI...,95183,1-1:1.29.0*255,23.04.2026,5304.0,04:15,-0.017
1,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:1.29.0*255,28.04.2026,5236.0,01:15,-16777.216
2,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:2.29.0*255,29.04.2026,5236.0,20:15,-0.256
3,../../store/parquet_data/2026/April 2026/LG_AI...,166902,1-1:2.29.0*255,29.04.2026,5236.0,20:45,-16777.216
4,../../store/parquet_data/2026/Februar 2026/LG_...,105491,1-1:1.29.0*255,28.02.2026,5504.0,04:15,-2.615
...,...,...,...,...,...,...,...
2132,../../store/parquet_data/2023/2023/September 2...,61016,1-1:1.29.0*255,04.09.2023,4310.0,05:00,-0.314
2133,../../store/parquet_data/2023/2023/September 2...,31024,1-1:1.29.0*255,30.09.2023,5726.0,23:45,-6.670
2134,../../store/parquet_data/2023/2023/September 2...,40887,1-1:1.29.0*255,02.09.2023,4310.0,10:30,-1.555
2135,../../store/parquet_data/2023/2023/September 2...,40887,1-1:1.29.0*255,12.09.2023,4310.0,11:00,-0.426
2136,../../store/parquet_data/2023/2023/September 2...,26103,1-1:1.29.0*255,15.09.2023,5313.0,13:15,-0.321

In [4]:
unique_mpids = negatives["MP ID"].unique()
unique_mpids

array([np.int64(95183), np.int64(166902), np.int64(105491),
       np.int64(65532), np.int64(60854), np.int64(29230),
       np.int64(163761), np.int64(484), np.int64(168419),
       np.int64(165291), np.int64(49554), np.int64(156396),
       np.int64(109577), np.int64(100196), np.int64(38459),
       np.int64(121704), np.int64(31024), np.int64(57344),
       np.int64(32769), np.int64(30223), np.int64(84020), np.int64(99753),
       np.int64(111270), np.int64(54312), np.int64(73323),
       np.int64(81567), np.int64(37862), np.int64(119217),
       np.int64(124902), np.int64(122184), np.int64(95396),
       np.int64(88023), np.int64(138629), np.int64(111623),
       np.int64(11406), np.int64(134166), np.int64(60475),
       np.int64(106193), np.int64(113715), np.int64(76527),
       np.int64(104725), np.int64(49289), np.int64(52799),
       np.int64(61139), np.int64(138226), np.int64(96989),
       np.int64(60033), np.int64(130205), np.int64(7412), np.int64(67346),
       np.int64(40887), np.int64(115385), np.int64(94304),
       np.int64(87201), np.int64(79257), np.int64(120768),
       np.int64(64375), np.int64(54777), np.int64(77332), np.int64(82724),
       np.int64(109784), np.int64(29468), np.int64(29508),
       np.int64(139391), np.int64(55966), np.int64(54653),
       np.int64(43549), np.int64(87041), np.int64(42193),
       np.int64(128643), np.int64(40326), np.int64(98803),
       np.int64(32121), np.int64(83650), np.int64(38488),
       np.int64(108236), np.int64(103624), np.int64(41019),
       np.int64(91110), np.int64(111746), np.int64(38387),
       'CH1011701234500000000000000349983',
       'CH1011701234500000000000000507844',
       'CH1011701234500000000000002125044',
       'CH1011701234500000000000000512076',
       'CH1011701234500000000000000527602',
       'CH1011701234500000000000000541561',
       'CH1011701234500000000000000557546',
       'CH1011701234500000000000002099327',
       'CH1011701234500000000000002099404',
       'CH1011701234500000000000000578168',
       'CH1011701234500000000000000600934',
       'CH1011701234500000000000000535216',
       'CH1011701234500000000000000536910',
       'CH1011701234500000000000000546300',
       'CH1011701234500000000000000548647',
       'CH1011701234500000000000000553425',
       'CH1011701234500000000000000574435',
       'CH1011701234500000000000000580579',
       'CH1011701234500000000000000599230',
       'CH1011701234500000000000002094042',
       'CH1011701234500000000000000525294',
       'CH1011701234500000000000000527464',
       'CH1011701234500000000000000552805',
       'CH1011701234500000000000000575709',
       'CH1011701234500000000000000604644',
       'CH1011701234500000000000000616322',
       'CH1011701234500000000000002087444',
       'CH1011701234500000000000002091631',
       'CH1011701234500000000000002106399',
       'CH1011701234500000000000000520181',
       'CH1011701234500000000000000540949',
       'CH1011701234500000000000000549133',
       'CH1011701234500000000000000553241',
       'CH1011701234500000000000000555535',
       'CH1011701234500000000000000617052',
       'CH1011701234500000000000002084318',
       'CH1011701234500000000000000531978',
       'CH1011701234500000000000000572378',
       'CH1011701234500000000000000607324',
       'CH10117012345SMLAB000000000000012',
       'CH1011701234500000000000000567065',
       'CH1011701234500000000000002087854',
       'CH1011701234500000000000002090455',
       'CH1011701234500000000000000505296',
       'CH1011701234500000000000000511008',
       'CH1011701234500000000000000535490',
       'CH1011701234500000000000000551642',
       'CH1011701234500000000000000555225',
       'CH1011701234500000000000000579234',
       'CH1011701234500000000000000594443',
       'CH1011701234500000000000002089308', np.int64(53628),
       np.int64(40310), np.int64(74778), np.int64(37450), np.int64(45899),
       np.int64(71942), np.int64(43121), np.int64(34506), np.int64(34428),
       np.int64(49926), np.int64(38238), np.int64(60702), np.int64(81015),
       np.int64(60049), np.int64(52920), np.int64(61957), np.int64(33997),
       np.int64(29407), np.int64(66139), np.int64(61673), np.int64(44233),
       np.int64(48163), np.int64(48367), np.int64(74319), np.int64(47073),
       np.int64(58221), np.int64(63425), np.int64(65965), np.int64(61003),
       np.int64(28554), np.int64(50052), np.int64(37388), np.int64(67433),
       np.int64(56953), np.int64(59907), np.int64(59978), np.int64(52383),
       np.int64(32830), np.int64(82956), np.int64(42897), np.int64(77468),
       np.int64(37823), np.int64(80776), np.int64(64326), np.int64(41721),
       np.int64(61016), np.int64(26103)], dtype=object)

In [5]:
import pandas as pd

# --------------------------------------------------
# 1. Load the three lookup tables
# --------------------------------------------------

mpid_map = pd.read_parquet(
    "../../store/parquet_data/mpid_zähler_mapping.parquet"
)

zaehler_gp = pd.read_parquet(
    "../../store/parquet_data/Zähler-GP.parquet"
)

gigi = pd.read_parquet(
    "../../store/parquet_data/HackDays2026 - GIGI.parquet"
)

# Clean column names
mpid_map.columns = mpid_map.columns.str.strip()
zaehler_gp.columns = zaehler_gp.columns.str.strip()
gigi.columns = gigi.columns.str.strip()


# --------------------------------------------------
# 2. Normalize IDs so joins work reliably
# --------------------------------------------------

mpid_map["MP ID"] = pd.to_numeric(
    mpid_map["MP ID"],
    errors="coerce"
).astype("Int64")

zaehler_gp["GPartner"] = pd.to_numeric(
    zaehler_gp["GPartner"],
    errors="coerce"
).astype("Int64")

gigi["GP-Nr"] = pd.to_numeric(
    gigi["GP-Nr"],
    errors="coerce"
).astype("Int64")


# --------------------------------------------------
# 3. Convert GIGI PV field into clean labels
# --------------------------------------------------

gigi["PV"] = (
    gigi["PV"]
    .astype(str)
    .str.strip()
    .str.lower()
)

gigi["has_pv"] = gigi["PV"].map({
    "x": True,
    "-": False
})


# --------------------------------------------------
# 4. Start ONLY with the unique MP IDs you found
#    in the negative-reading dataset
# --------------------------------------------------

mpids = pd.DataFrame({
    "MP ID": pd.Series(unique_mpids, dtype="Int64")
})


# --------------------------------------------------
# 5. MP ID -> Zählpunktbezeichnung
# --------------------------------------------------

matched = mpids.merge(
    mpid_map[["MP ID", "Zählpunktbezeichnung"]],
    on="MP ID",
    how="left"
)


# --------------------------------------------------
# 6. Zählpunktbezeichnung -> GPartner
# --------------------------------------------------

matched = matched.merge(
    zaehler_gp[
        ["Zählpunktbezeichnung", "GPartner"]
    ],
    on="Zählpunktbezeichnung",
    how="left"
)


# --------------------------------------------------
# 7. GPartner -> GP-Nr in GIGI -> PV
# --------------------------------------------------

matched = matched.merge(
    gigi[["GP-Nr", "PV", "has_pv"]],
    left_on="GPartner",
    right_on="GP-Nr",
    how="left"
)

matched.head()

ValueError: invalid literal for int() with base 10: 'CH1011701234500000000000000349983'

In [6]:
clean_mpids = (
    pd.to_numeric(
        pd.Series(unique_mpids),
        errors="coerce"
    )
    .dropna()
    .astype("Int64")
    .drop_duplicates()
)

mpids = pd.DataFrame({
    "MP ID": clean_mpids
})

print("Original unique values:", len(unique_mpids))
print("Valid numeric MP IDs:", len(mpids))

Original unique values: 179
Valid numeric MP IDs: 128

In [7]:
all_mpids = pd.Series(unique_mpids)

bad_values = all_mpids[
    pd.to_numeric(all_mpids, errors="coerce").isna()
].drop_duplicates()

print("Bad/non-numeric values:", len(bad_values))
print(bad_values.tolist())

Bad/non-numeric values: 51
['CH1011701234500000000000000349983', 'CH1011701234500000000000000507844', 'CH1011701234500000000000002125044', 'CH1011701234500000000000000512076', 'CH1011701234500000000000000527602', 'CH1011701234500000000000000541561', 'CH1011701234500000000000000557546', 'CH1011701234500000000000002099327', 'CH1011701234500000000000002099404', 'CH1011701234500000000000000578168', 'CH1011701234500000000000000600934', 'CH1011701234500000000000000535216', 'CH1011701234500000000000000536910', 'CH1011701234500000000000000546300', 'CH1011701234500000000000000548647', 'CH1011701234500000000000000553425', 'CH1011701234500000000000000574435', 'CH1011701234500000000000000580579', 'CH1011701234500000000000000599230', 'CH1011701234500000000000002094042', 'CH1011701234500000000000000525294', 'CH1011701234500000000000000527464', 'CH1011701234500000000000000552805', 'CH1011701234500000000000000575709', 'CH1011701234500000000000000604644', 'CH1011701234500000000000000616322', 'CH1011701234500000000000002087444', 'CH1011701234500000000000002091631', 'CH1011701234500000000000002106399', 'CH1011701234500000000000000520181', 'CH1011701234500000000000000540949', 'CH1011701234500000000000000549133', 'CH1011701234500000000000000553241', 'CH1011701234500000000000000555535', 'CH1011701234500000000000000617052', 'CH1011701234500000000000002084318', 'CH1011701234500000000000000531978', 'CH1011701234500000000000000572378', 'CH1011701234500000000000000607324', 'CH10117012345SMLAB000000000000012', 'CH1011701234500000000000000567065', 'CH1011701234500000000000002087854', 'CH1011701234500000000000002090455', 'CH1011701234500000000000000505296', 'CH1011701234500000000000000511008', 'CH1011701234500000000000000535490', 'CH1011701234500000000000000551642', 'CH1011701234500000000000000555225', 'CH1011701234500000000000000579234', 'CH1011701234500000000000000594443', 'CH1011701234500000000000002089308']

In [8]:
clean_mpids = (
    pd.to_numeric(
        pd.Series(unique_mpids),
        errors="coerce"
    )
    .dropna()
    .astype("Int64")
    .drop_duplicates()
)

mpids = pd.DataFrame({
    "MP ID": clean_mpids
})

In [9]:
bad = pd.to_numeric(
    negatives["MP ID"],
    errors="coerce"
).isna()

print("Invalid MP IDs:", bad.sum())

Invalid MP IDs: 194

In [10]:
from pathlib import Path
import pandas as pd

root = Path("../../store/parquet_data")

dates = []

for year in ["2023", "2026"]:
    for file in (root / year).rglob("*.parquet"):
        df = pd.read_parquet(file, columns=["Datum"])

        d = pd.to_datetime(
            df["Datum"],
            format="%d.%m.%Y",
            errors="coerce"
        )

        dates.append(d.min())
        dates.append(d.max())

print("First date:", min(dates))
print("Last date:", max(dates))

First date: 2023-01-01 00:00:00
Last date: 2026-07-31 00:00:00

In [11]:
from pathlib import Path
import pandas as pd

root = Path("../../store/parquet_data")

all_mpids = set()

for file in root.rglob("LG_AIM2Hackerdays*.parquet"):
    df = pd.read_parquet(file, columns=["MP ID"])

    mpids = pd.to_numeric(df["MP ID"], errors="coerce").dropna()
    all_mpids.update(mpids.astype(int).unique())

print("Households with time-series data:", len(all_mpids))

Households with time-series data: 92840

In [12]:
for year in ["2023", "2024", "2025", "2026"]:
    year_mpids = set()

    for file in (root / year).rglob("*.parquet"):
        try:
            df = pd.read_parquet(file, columns=["MP ID"])
            ids = pd.to_numeric(df["MP ID"], errors="coerce").dropna()
            year_mpids.update(ids.astype(int).unique())
        except Exception:
            pass

    print(year, len(year_mpids))

2023 0
2024 52845
2025 79167
2026 90675